### ISSUE TITLE
1.0 Roadmap

### ISSUE THREAD

**Issue by klaaspieter** [klaaspieter/Numeric#3]
- [ ] Use the new Xcode 6.3 playgrounds to explain things in more detail
- [ ] Better README / documentation
- [ ] Add `atX` (endOfDay, Noon, etc) methods
- [ ] Add `currentX` (month, day, year, etc)  methods 
- [x] Date constructor that accepts individual date components
